#!/bin/sh
set -e

if [ "$(uname -s)" = "Darwin" ]; then
    brew update
    brew install qt

    case "$CONFIG" in
    full*)
        brew install doxygen qt-gstreamer
        ;;
    esac
else
    sudo apt-get update -qq
    sudo apt-get install -qq clang cmake qtbase5-dev

    case "$CONFIG" in
    full*)
        sudo apt-get install -qq  doxygen libqt5gstreamer-1.0-0 libqt5gstreamer-dev
        ;;
    esac
fi
